# Generated by Django 5.1.2 on 2025-09-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('tractor', 'Tractor'), ('plough', 'Plough'), ('harvester', 'Harvester'), ('seeder', 'Seeder'), ('other', 'Other')], default='other', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('center_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.DecimalField(decimal_places=3, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=20)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_sent', models.BooleanField(default=False)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.geofence')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('is_inside', models.BooleanField(default=False)),
                ('last_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.geofence')),
            ],
            options={
                'unique_together': {('device_id', 'geofence')},
            },
        ),
    ]
